[package]
name = "my-redis"
version = "0.1.0"
edition = "2021"
default-run = "my-redis"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["full"]}
mini-redis = "0.4"

[[bin]]
name = "redis_client"